version: "3.7"
services:
  animalinfo-backend:
    image: animalinfo-backend:220908
    container_name: animalinfo-backend
    # command: npm start
    restart: unless-stopped
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
