-- DROP DATABASE IF EXISTS test_db;   
-- CREATE DATABASE IF NOT EXISTS test_db;   
USE test_db; 

DROP TABLE IF EXISTS DATA; 

CREATE TABLE IF NOT EXISTS DATA 
  ( 
   `id` varchar(45) NOT NULL,
  `userId` int(11) DEFAULT NULL,
  `refer` varchar(45) DEFAULT NULL,
  `price` varchar(2048) DEFAULT NULL,
  `data_type` varchar(45) DEFAULT NULL,
  `species` varchar(45) DEFAULT NULL,
  `race` varchar(45) DEFAULT NULL,
  `birth` varchar(45) DEFAULT NULL,
  `sex` varchar(45) DEFAULT NULL,
  `weight` varchar(45) DEFAULT NULL,
  `shoulderHeight` int(11) DEFAULT NULL,
  `neckSize` int(11) DEFAULT NULL,
  `backLength` int(11) DEFAULT NULL,
  `chestSize` int(11) DEFAULT NULL,
  `BCS` int(11) DEFAULT NULL,
  `exercise` int(11) DEFAULT NULL,
  `foodCount` int(11) DEFAULT NULL,
  `environment` int(11) DEFAULT NULL,
  `defecation` int(11) DEFAULT NULL,
  `foodAmount` int(11) DEFAULT NULL,
  `snackAmount` int(11) DEFAULT NULL,
  `foodKind` int(11) DEFAULT NULL,
  `disease` varchar(45) DEFAULT NULL,
  `diseaseName` varchar(45) DEFAULT NULL,
  `CPR` int(11) DEFAULT NULL,
  `lgG` int(11) DEFAULT NULL,
  `IL6` int(11) DEFAULT NULL,
  `AFP` int(11) DEFAULT NULL,
  `heartRate` int(11) DEFAULT NULL,
  `breatingRate` int(11) DEFAULT NULL,
  `bodyHeat` int(11) DEFAULT NULL,
  `stress` int(11) DEFAULT NULL,
  `a01` varchar(500) DEFAULT NULL,
  `a02` varchar(500) DEFAULT NULL,
  `a03` varchar(500) DEFAULT NULL,
  `a04` varchar(500) DEFAULT NULL,
  `a05` varchar(500) DEFAULT NULL,
  `a06` varchar(500) DEFAULT NULL,
  `a07` varchar(500) DEFAULT NULL,
  `a08` varchar(500) DEFAULT NULL,
  `a09` varchar(500) DEFAULT NULL,
  `a10` varchar(500) DEFAULT NULL,
  `a11` varchar(500) DEFAULT NULL,
  `a12` varchar(500) DEFAULT NULL,
  `a13` varchar(500) DEFAULT NULL,
  `a14` varchar(500) DEFAULT NULL,
  `a15` varchar(500) DEFAULT NULL,
  `a16` varchar(500) DEFAULT NULL,
  `a17` varchar(500) DEFAULT NULL,
  `a18` varchar(500) DEFAULT NULL,
  `a19` varchar(500) DEFAULT NULL,
  `a20` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `userId` (`userId`),
  CONSTRAINT `DATA_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `USERS` (`id`)
  );
--   작성중